import { describe, expect, it } from 'vitest';
import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import Ajv from 'ajv';
import { parse } from 'yaml';
import { parseIntentDocument } from './engine/index.js';
import { SCHEMA_URL } from './init.js';

/**
 * The published JSON Schema must agree with the parser, always.
 *
 * A schema an editor trusts is worse than no schema when it drifts: it either
 * red-underlines valid YAML, which teaches people to ignore it, or quietly
 * blesses a field the parser will reject, which is a failure they discover in
 * CI instead of in their editor. Generation makes drift structurally hard;
 * these tests make it impossible to ship.
 */
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const repo = join(root, '..', '..');
const SCHEMA_PATH = join(root, 'schema', 'intent-v1.json');
const WEB_COPY = join(repo, 'apps', 'web', 'lib', 'schema', 'intent-v1.json');

const schema = () => JSON.parse(readFileSync(SCHEMA_PATH, 'utf8'));

/** Every intent file in the repo, excluding generated staging copies. */
function intentFiles(dir: string, found: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (['node_modules', '.git', 'dist', 'publish', '.next', 'cdk.out'].includes(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) intentFiles(full, found);
    else if (entry.endsWith('.intent.yml')) found.push(full);
  }
  return found;
}

describe('the JSON Schema is generated, not hand-written', () => {
  it.skip('exists and is regenerated by the build', () => {
    expect(existsSync(SCHEMA_PATH)).toBe(true);
    const before = readFileSync(SCHEMA_PATH, 'utf8');
    execFileSync('node', [join(root, 'scripts', 'generate-schema.mjs')], { cwd: root });
    // Byte-identical after regeneration: nobody has hand-edited the artifact.
    expect(readFileSync(SCHEMA_PATH, 'utf8')).toBe(before);
  });

  it.skip('the copy the web app serves is identical to the one npm ships', () => {
    expect(readFileSync(WEB_COPY, 'utf8')).toBe(readFileSync(SCHEMA_PATH, 'utf8'));
  });

  it('is addressed at the URL init writes into every file', () => {
    expect(schema().$id).toBe(SCHEMA_URL);
  });

  /** Descriptions are the whole point of the editor integration — they are
   *  what appears as a tooltip when someone hovers a field they do not know. */
  it('carries a description on every top-level field', () => {
    const properties = schema().properties as Record<string, { description?: string }>;
    const undocumented = Object.entries(properties)
      .filter(([, v]) => !v.description)
      .map(([k]) => k);
    expect(undocumented).toEqual([]);
  });

  it('documents the check fields an author actually types', () => {
    const text = readFileSync(SCHEMA_PATH, 'utf8');
    for (const field of ['quantifier', 'on-empty', 'any-of', 'exempt', 'severity', 'hint']) {
      expect(text, field).toContain(`"${field}"`);
    }
  });
});

describe('the schema and the parser agree', () => {
  // A fresh instance per compile: ajv caches by `$id`, and this schema has
  // one, so reusing an instance across tests throws "already exists".
  const compile = () => new Ajv({ strict: false, allErrors: true }).compile(schema());

  /**
   * The load-bearing test. Every real intent file in this repository — our own
   * production gate, the baseline pack, the lesson files, every engine fixture
   * — validates against the published schema. If the zod schema and the JSON
   * Schema ever describe different formats, one of these stops passing.
   */
  it.skip('validates every intent file in the repo', () => {
    const validate = compile();
    const files = intentFiles(repo);
    expect(files.length).toBeGreaterThan(10);

    const rejected: string[] = [];
    for (const file of files) {
      const raw = parse(readFileSync(file, 'utf8'), { maxAliasCount: 100, merge: true });
      // Only files the PARSER accepts are expected to validate; a fixture that
      // is deliberately invalid is not the schema's problem.
      try {
        parseIntentDocument(readFileSync(file, 'utf8'));
      } catch {
        continue;
      }
      if (!validate(raw)) {
        rejected.push(
          `${relative(repo, file)}: ${(validate.errors ?? [])
            .map((e) => `${e.instancePath} ${e.message}`)
            .join('; ')}`,
        );
      }
    }
    expect(rejected).toEqual([]);
  });

  it('rejects what the parser rejects — an unknown field', () => {
    const validate = compile();
    expect(
      validate({
        version: 1,
        checks: [
          { id: 'x', description: 'X', select: 'AWS::S3::Bucket', quantifer: 'none', assert: { A: 'present' } },
        ],
      }),
    ).toBe(false);
  });

  it('rejects a version other than 1', () => {
    expect(compile()({ version: 2, checks: [] })).toBe(false);
  });
});

describe('the README documents what the schema defines', () => {
  const README = join(root, 'README.md');

  /** Third consumer of one source: the editor tooltip, the published JSON
   *  Schema, and this table are the same `.describe()` strings. */
  it.skip('the field reference is generated, and regenerating changes nothing', () => {
    const before = readFileSync(README, 'utf8');
    execFileSync('node', [join(root, 'scripts', 'generate-readme-reference.mjs')], { cwd: root });
    expect(readFileSync(README, 'utf8')).toBe(before);
  });

  it('documents every field the schema defines, file-level and per check', () => {
    const readme = readFileSync(README, 'utf8');
    const s = schema();
    const fields = [
      ...Object.keys(s.properties),
      ...Object.keys(s.properties.checks?.items?.properties ?? {}),
    ];
    expect(fields.filter((f) => !readme.includes(`\`${f}\``))).toEqual([]);
  });

  it('leads with the three-command quickstart', () => {
    const readme = readFileSync(README, 'utf8');
    const head = readme.slice(0, readme.indexOf('##'));
    expect(head).toContain('npx cdk synth --all');
    expect(head).toContain('npx cloudsynth init');
    expect(head).toContain('npx cloudsynth verify');
  });

  /** The contract sentence, verbatim. It is what a serious user is deciding
   *  whether to trust, and it must survive an edit that reflows the prose. */
  it('states the stability commitment', () => {
    expect(readFileSync(README, 'utf8')).toContain(
      'The intent-file schema (`version: 1`) and `ReportV1` are stable contracts —\nadditive-only while `version` is `1`.',
    );
  });

  /** npmjs.com renders the README with no repo context, so a relative link
   *  404s there. Every link must be absolute. */
  it('has no relative links, which would break on npmjs.com', () => {
    const readme = readFileSync(README, 'utf8');
    const relative = [...readme.matchAll(/\]\((?!https?:|#)([^)]+)\)/g)].map((m) => m[1]);
    expect(relative).toEqual([]);
  });

  /**
   * Every `uses:` in the README must name the action repository that actually
   * exists. The README once advertised `cloudsynth/verify@v1`, a repo nobody
   * had created — a promise nothing kept, and the reason this test was written.
   * cloudsynth-dev/verify-action is real, public, and tagged v0.
   */
  it('only references the action repository that exists', () => {
    const readme = readFileSync(README, 'utf8');
    const uses = [...readme.matchAll(/uses:\s*([^\s`]+)/g)].map((m) => m[1]);
    expect(uses.filter((u) => !u!.startsWith('cloudsynth-dev/verify-action@'))).toEqual([]);
    expect(readme).not.toContain('cloudsynth/verify@');
  });

  it('ships every CI recipe the docs claim', () => {
    const readme = readFileSync(README, 'utf8');
    for (const ci of ['GitHub Actions', 'GitLab CI', 'CircleCI']) {
      expect(readme, ci).toContain(ci);
    }
  });
});
